# The URL the site will be built for
base_url = "https://blog.trovezero.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Theme: https://www.getzola.org/themes/apollo/
theme = "apollo"

output_dir = "target"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here

stylesheets = ["custom.css"]

menu = [
]

socials = [
    { name = "twitter", url = "https://twitter.com/trove_zero", icon = "twitter" },
    { name = "github", url = "https=//github.com/trovezero", icon = "github" },
]